SELECT DISTINCT ?x0  WHERE {<http://dbpedia.org/resource/We_Are_Marshall> <http://dbpedia.org/ontology/director> ?x0 .  <http://dbpedia.org/resource/We_Are_Marshall> <http://dbpedia.org/ontology/starring> <http://dbpedia.org/resource/Matthew_Fox_%28actor%29> .  <http://dbpedia.org/resource/We_Are_Marshall> <http://dbpedia.org/ontology/starring> <http://dbpedia.org/resource/Kate_Mara> .  <http://dbpedia.org/resource/Party_of_Five> <http://dbpedia.org/ontology/starring> <http://dbpedia.org/resource/Matthew_Fox_%28actor%29> .  <http://dbpedia.org/resource/Matthew_Fox_%28actor%29> <http://dbpedia.org/property/birthplace> <http://dbpedia.org/resource/United_States> .   }  LIMIT 200 OFFSET 0