SELECT DISTINCT ?x0 ?x1  WHERE {?x0 <http://dbpedia.org/ontology/director> ?x1 .  ?x0 <http://dbpedia.org/ontology/starring> <http://dbpedia.org/resource/Matthew_Fox_%28actor%29> .  <http://dbpedia.org/resource/Party_of_Five> <http://dbpedia.org/ontology/starring> <http://dbpedia.org/resource/Matthew_Fox_%28actor%29> .  <http://dbpedia.org/resource/Matthew_Fox_%28actor%29> <http://dbpedia.org/property/birthplace> <http://dbpedia.org/resource/United_States> .   }  LIMIT 200 OFFSET 0