PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>  SELECT  ?tip ?abstract ?poza WHERE   { ?tip  skos:subject          <http://dbpedia.org/resource/Category:Computer_printers> ;           <http://dbpedia.org/ontology/abstract>  ?abstract .     FILTER langMatches(lang(?abstract), 'en')     FILTER regex(?abstract, 'laser')     ?tip  <http://dbpedia.org/ontology/thumbnail>  ?poza .   } LIMIT   1 