SELECT *    WHERE      {         ?motorway  a                                              <http://dbpedia.org/ontology/Road>  .        ?motorway <http://dbpedia.org/ontology/length>    ?length   .        ?motorway <http://xmlns.com/foaf/0.1/name>    ?name               }   LIMIT 20