PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX  dbo:  <http://dbpedia.org/ontology/> PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>  SELECT DISTINCT  ?entita ?nome ?prop ?valoreProprieta WHERE   { ?entita  rdf:type    dbo:Artist ;              rdfs:label  ?nome ;              ?prop       ?valoreProprieta .     FILTER ( ?nome = 'Russell Crowe'@en )   } LIMIT   200 