     PREFIX foaf: <http://xmlns.com/foaf/0.1/>     PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>     PREFIX prop: <http://dbpedia.org/property/>     PREFIX dbowl: <http://dbpedia.org/ontology/>     SELECT ?page ?label     WHERE {             ?title dbowl:author <http://dbpedia.org/resource/Haruki_Murakami> .       ?title foaf:page ?page .       ?title rdfs:label ?label       filter(lang(?label)='en')     }     LIMIT 10