PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX  dbpedia-owl: <http://dbpedia.org/ontology/> PREFIX  p:    <http://dbpedia.org/property/> PREFIX  dbpedia: <http://dbpedia.org/resource/>  SELECT DISTINCT  ?movie ?title WHERE   { ?movie  <http://www.w3.org/1999/02/22-rdf-syntax-ns#type>  dbpedia-owl:Film ;             rdfs:label            ?title .     ?title  <bif:contains>        'splice' .     FILTER ( lang(?title) = 'en' )   } LIMIT   10 