PREFIX dbpedia: <http://dbpedia.org/ontology/> PREFIX dbprop: <http://dbpedia.org/property/> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX foaf: <http://xmlns.com/foaf/0.1/>  select distinct ?artistName ?occupation where { 	<http://dbpedia.org/resource/Paz_Vega>  rdfs:label ?artistName.         { 		OPTIONAL {  			<http://dbpedia.org/resource/Paz_Vega> dbprop:occupation ?occupation. FILTER ( REGEX(?occupation, 'director', 'i') || REGEX(?occupation, 'actress', 'i') ). 	}. 	} UNION { 		OPTIONAL {  			<http://dbpedia.org/resource/Paz_Vega> dbpedia:occupation ?occupation. FILTER (?occupation = <http://dbpedia.org/resource/Film_director>). 		} 	}          FILTER (LANG(?artistName) = 'en'). }