PREFIX  :     <http://dbpedia.org/resource/> PREFIX  dc:   <http://purl.org/dc/elements/1.1/> PREFIX  dbpedia2: <http://dbpedia.org/property/> PREFIX  dbpedia-owl: <http://dbpedia.org/ontology/> PREFIX  foaf: <http://xmlns.com/foaf/0.1/> PREFIX  georss: <http://www.georss.org/georss/> PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX  dbo:  <http://dbpedia.org/ontology/> PREFIX  dbpedia: <http://dbpedia.org/> PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#> PREFIX  owl:  <http://www.w3.org/2002/07/owl#> PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>  SELECT  ?abs WHERE   { ?subject  rdf:type              dbpedia-owl:Place ;               dbpedia2:location     :London ;               dbpedia-owl:abstract  ?abs .     FILTER ( lang(?abs) = 'en' )   } 