PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>  SELECT DISTINCT ?cname WHERE {   ?country rdf:type dbpedia-owl:Country .   ?country skos:subject <http://dbpedia.org/resource/Category:European_countries> .   ?country rdfs:label ?cname    . FILTER ( lang(?cname) = 'en' ) }