PREFIX dbpedia: <http://dbpedia.org/ontology/> PREFIX dbpedia_property: <http://dbpedia.org/property/> SELECT DISTINCT ?s  WHERE  { <http://dbpedia.org/resource/The_Sixth_Sense> ?p ?s.  ?s dbpedia_property:name ?o;  a dbpedia:Person.  FILTER (regex(?o,'Bruce')) }