PREFIX owl: <http://www.w3.org/2002/07/owl#> PREFIX xsd: <http://www.w3.org/2001/XMLSchema#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX dc: <http://purl.org/dc/elements/1.1/> PREFIX resource: <http://dbpedia.org/resource/> PREFIX property: <http://dbpedia.org/property/> PREFIX dbpedia: <http://dbpedia.org/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX dbo: <http://dbpedia.org/ontology/> PREFIX opencyc: <http://sw.opencyc.org/2008/06/10/concept/en/>  SELECT DISTINCT ?name ?population WHERE {      ?city rdf:type dbo:Settlement .      ?city foaf:name ?name .      ?city dbo:populationTotal ?population .      FILTER (?population > 1000000) . } ORDER BY ?name