PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX resource: <http://dbpedia.org/resource/> PREFIX property: <http://dbpedia.org/property/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX dbo: <http://dbpedia.org/ontology/> PREFIX category: <http://dbpedia.org/resource/Category:>  SELECT DISTINCT ?id WHERE { ?id skos:subject ?usc { ?usc skos:broader category:Cities_in_the_United_States_by_state } ?id dbo:populationTotal ?populationTotal . FILTER (?populationTotal > 300000) } ORDER BY ?id