  PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX : <http://dbpedia.org/resource/> PREFIX dbpedia2: <http://dbpedia.org/property/>  PREFIX dbpedia: <http://dbpedia.org/>  PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX books:   <http://example.org/book/> PREFIX dc:      <http://purl.org/dc/elements/1.1/> PREFIX geo: <http://www.georss.org/georss/>   SELECT DISTINCT ?name ?loc WHERE {  ?Prefecture skos:subject <http://dbpedia.org/resource/Category:Convention_centers_in_Japan>. ?Prefecture geo:point ?loc. ?Prefecture dbpedia2:name ?name.  } ORDER BY ?name