PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX resource: <http://dbpedia.org/resource/> PREFIX property: <http://dbpedia.org/property/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX dbo: <http://dbpedia.org/ontology/>  SELECT DISTINCT ?id WHERE { { ?id rdf:type dbo:River . } UNION { ?id rdf:type dbo:Stream . } ?id property:country ?country FILTER (str(?country) = 'United States' || ?country = resource:United_States) } ORDER BY ?id