select ?prop ?val where{ {<http://dbpedia.org/resource/Port_Moresby> ?prop ?val FILTER regex(?val, '/class/')} union        {<http://dbpedia.org/resource/Port_Moresby> ?prop ?val FILTER regex(?prop, 'geo')} union        {<http://dbpedia.org/resource/Port_Moresby> ?prop ?val FILTER regex(?prop, 'subject')} union        {<http://dbpedia.org/resource/Port_Moresby> ?prop ?val FILTER regex(?prop, 'property/name')} union        {<http://dbpedia.org/resource/Port_Moresby> ?prop ?val FILTER regex(?prop, 'property/popula')} union        {<http://dbpedia.org/resource/Port_Moresby> ?prop ?val FILTER regex(?prop, 'property/name')} union        {<http://dbpedia.org/resource/Port_Moresby> ?prop ?val FILTER regex(?prop, 'property/cap')}    } 