PREFIX  dbpedia2: <http://dbpedia.org/property/> PREFIX  dbo:  <http://dbpedia.org/ontology/> PREFIX  foaf: <http://xmlns.com/foaf/0.1/> PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>  SELECT  ?name ?gebdat WHERE   { ?person  dbpedia2:birthPlace  <http://dbpedia.org/resource/Berlin> ;              dbo:birthDate        ?gebdat ;              foaf:name            ?name .     FILTER ( ?gebdat < '1900-01-01'^^xsd:date )     FILTER ( ?gebdat > '1800-01-01'^^xsd:date )   } ORDER BY ASC(?gebdat) 