PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX resource: <http://dbpedia.org/resource/> PREFIX property: <http://dbpedia.org/property/> PREFIX skos: <http://www.w3.org/2004/02/skos/core#> PREFIX dbo: <http://dbpedia.org/ontology/>  SELECT DISTINCT ?id WHERE {   ?id rdf:type dbo:Settlement .   ?id dbo:populationTotal ?populationTotal .   ?id property:subdivisionName ?subdivisionName .   OPTIONAL { ?id property:settlementType ?settlementType } .   FILTER (?subdivisionName = resource:United_States || str(?subdivisionName) = 'United_States' || str(?subdivisionName) = 'United States')   FILTER (str(?settlementType) != 'Borough of New York City')   FILTER (?settlementType != resource:United_States_metropolitan_area)   FILTER (?populationTotal > 1000000 && ?populationTotal < 40000000)   FILTER (?settlementType != resource:Fictional_location) } ORDER BY ?id