PREFIX  foaf: <http://xmlns.com/foaf/0.1/> PREFIX  terms: <http://purl.org/dc/terms/> PREFIX  timeline: <http://purl.org/NET/c4dm/timeline.owl#> PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX  address: <http://schemas.talis.com/2005/address/schema#> PREFIX  event: <http://purl.org/NET/c4dm/event.owl#> PREFIX  emocom: <http://www.emotion-and-computing.de/resource/> PREFIX  bibo: <http://purl.org/ontology/bibo/> PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#> PREFIX  owl:  <http://www.w3.org/2002/07/owl#> PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>  SELECT DISTINCT  ?label ?page WHERE   { <http://dbpedia.org/resource/Jackey_Jackey>               skos:subject  ?resource .     ?resource  rdfs:label   ?label .     OPTIONAL       { ?resource  foaf:page  ?page .}     FILTER ( lang(?label) = 'en' )   } 