PREFIX  geo:  <http://www.w3.org/2003/01/geo/wgs84_pos#> PREFIX  foaf: <http://xmlns.com/foaf/0.1/> PREFIX  georss: <http://www.georss.org/georss/>  SELECT  * WHERE   { OPTIONAL       { <http://dbpedia.org/resource/Siero>                   geo:lat  ?lat .       }     OPTIONAL       { <http://dbpedia.org/resource/Siero>                   geo:long  ?long .       }     OPTIONAL       { <http://dbpedia.org/resource/Siero>                   foaf:depiction  ?depiction .       }     OPTIONAL       { <http://dbpedia.org/resource/Siero>                   foaf:homepage  ?homepage .       }   } 