PREFIX  dbpedia2: <http://dbpedia.org/property/> PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> PREFIX  geo:  <http://www.w3.org/2003/01/geo/wgs84_pos#> PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> PREFIX  skos: <http://www.w3.org/2004/02/skos/core#>  SELECT  ?museum ?com ?name ?lat ?long WHERE   { ?museum  skos:subject  <http://dbpedia.org/resource/Category:Museums_in_Paris> .     OPTIONAL       { { ?museum  rdfs:comment  ?com .}         FILTER ( lang(?com) = 'en' )         ?museum  rdfs:label  ?name ;                  geo:lat     ?lat ;                  geo:long    ?long .         FILTER ( lang(?name) = 'en' )       }   } LIMIT   10 