PREFIX foaf: <http://xmlns.com/foaf/0.1/> PREFIX owl: <http://www.w3.org/2002/07/owl#> PREFIX ont: <http://dbpedia.org/ontology/> PREFIX prop: <http://dbpedia.org/property/> PREFIX db: <http://dbpedia.org/resource/> PREFIX rdf: <http://www.w3.org/1999/02/22-rdfsyntax-ns#> PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> SELECT ?name ?seasons WHERE{ {?show prop:network ?network. FILTER regex(?network, 'HBO')} UNION {?show prop:network ?network. FILTER regex(?network, 'Showtime')}. ?show prop:showName ?name. ?show prop:numSeasons ?seasons. FILTER (?seasons > 4)}