 PREFIX dbpedia: <http://dbpedia.org/property/>  PREFIX dbpedia-owl:<http://dbpedia.org/ontology/>  PREFIX skos: <http://www.w3.org/2004/02/skos/core#>  PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>  PREFIX foaf: <http://xmlns.com/foaf/0.1/>   SELECT distinct ?label ?label_en ?label_it ?page ?kfor  WHERE   {   <http://dbpedia.org/resource/Category:Photovoltaics_manufacturers> rdfs:label ?label  .    FILTER (LANG(?label) = 'en') .   OPTIONAL {   ?subject skos:subject <http://dbpedia.org/resource/Category:Photovoltaics_manufacturers>.   FILTER (REGEX(?subject, '[^a-z A-Z 0-9]*')) . }     OPTIONAL {          ?subject rdfs:label  ?label_en .          FILTER (LANG(?label_en) = 'en') .            }   OPTIONAL {          ?subject rdfs:label  ?label_it .          FILTER (LANG(?label_it) = 'it') .            }   OPTIONAL {           ?subject foaf:page ?page .             }   OPTIONAL {             ?subject dbpedia-owl:knownFor   ?kfor .             }     }